### ISSUE TITLE
get_KOR_ticker() 에러

### ISSUE THREAD

**Issue by triptojoon** [hyunyulhenry/HenryQuant#1]
안녕하세요. 

HenryQuant를 잘 만들어주셔서 덕분에 편하게 사용하고 있습니다.
사용 중 에러가 생겨서 올려드립니다.

Warning: 3 parsing failures.
row col  expected    actual         file
 20  -- 1 columns 2 columns literal data
 25  -- 1 columns 2 columns literal data
127  -- 1 columns 2 columns literal data

Error: Can't subset columns that don't exist.
x Locations 2, 3, 4, and 7 don't exist.
i There are only 1 column.
Run `rlang::last_error()` to see where the error occurred.

감사합니다.

**Comment by hyunyulhenry** [comment]
책이 나와서 더이상 이패키지는 관리하고 있지 않습니다.

https://hyunyulhenry.github.io/quant_cookbook/

여기 5장에 해당 내용이 있으니 참고하시면 잘 돌아갑니다.

**Comment by triptojoon** [comment]
답변 감사합니다.
